micronaut:
  application:
    name: flowableClient
  server:
    port: 8081
  http:
    client:
#      read-idle-timeout: 1m
    services:
      sensors:
        urls:
          - http://localhost:8080
sensor:
  measurement:
    log:
      rate: 1 # seconds
    retry:
      wait: 2 # seconds

